---
ReverseProxy:
  Routes:
    StudentsService:
      ClusterId: StudentsService
      Match:
        Path: "/api/students"
      Transforms:
        - PathRemovePrefix: "/api"
    CoursesService:
      ClusterId: CoursesService
      Match:
        Path: "/api/courses"
      Transforms:
        - PathRemovePrefix: "/api"
    AdmissionService: 
      ClusterId: AdmissionService
      Match:
        Path: "/api/admissions"
      Transforms:
        - PathRemovePrefix: "/api"      
    FacultyService:
      ClusterId: FacultyService
      Match:
        Path: "/api/faculties"
      Transforms:
        - PathRemovePrefix: "/api"
  
  
  
  Clusters:
    StudentsService:
      Destinations:
        students-service:
          Address: http://localhost:8000/
    AdmissionService:
      Destinations:
        admission-service:
          Address: http://localhost:3000/
    FacultyService:
      Destinations:
        faculty-service:
          Address: http://localhost:3001/   
    CoursesService:
      Destinations:
        courses-service:
          Address: http://localhost:6000/
    